name: hail-remote
channels:
  - conda-forge
dependencies:
  - conda-forge::ipykernel=5.1.3
  - conda-forge::ipywidgets=7.5.1
  - conda-forge::matplotlib=3.1.2
  - conda-forge::nb_conda_kernels=2.2.2
  - conda-forge::notebook=6.0.1
  - conda-forge::numpy=1.17.3
  - conda-forge::pandas=0.25.3
  - conda-forge::python=3.7.3
